version: '3.7'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: majid_mongo_container_new
    ports:
      - "3031:27017"  
    volumes:
      - pritam_mongo_data:/data/db

  # Backend Service
  backend:
    build: 
      context: ./backend
    image: majid7991/backend:latest
    container_name: majid_backend_container_new
    depends_on:
      - mongo
    ports:
      - "5003:5000"
    environment:
      - MONGO_URI=mongodb://majid_mongo_container_new:27017/pritam_test_db  

  # Frontend Service
  frontend:
    build: 
      context: ./frontend
    image: majid7991/frontend:latest
    container_name: majid_frontend_container_new
    depends_on:
      - backend
    ports:
      - "8082:3000"

volumes:
  pritam_mongo_data:
