name: Build, Push, and Deploy using Docker Compose 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag images using Docker Compose
        run: |
          docker compose build
          docker tag majid7991/backend:latest majid7991/backend:${{ github.sha }}
          docker tag majid7991/frontend:latest majid7991/frontend:${{ github.sha }}

      - name: Push Images to Docker Hub
        run: |
          docker push majid7991/backend:latest
          docker push majid7991/frontend:latest
          docker push majid7991/backend:${{ github.sha }}
          docker push majid7991/frontend:${{ github.sha }}

      - name: Scan Backend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "majid7991/backend:latest"
          format: "table"
          exit-code: 0   # ✅ This ensures the pipeline does NOT fail
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Scan Frontend with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "majid7991/frontend:latest"
          format: "table"
          exit-code: 0
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
